/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108614-g37ee36f689-20221011"
#endif /* AVUTIL_FFVERSION_H */
